### PR TITLE
feat: add metadata of user task

### LINKED ISSUE #283: I can access user task's metadata
## Description

I can access the following static properties of a user task.

- the assignee 
- the candidate groups

Extend the GraphQL API to expose these properties as [element metadata](https://github.com/camunda-community-hub/zeeqs/blob/master/graphql-api/src/main/resources/graphql/Element.graphqls#L51-L64).

### PR DESCRIPTION
**Pull request by skayliu**
## Description
I can access the following static properties of a user task. 
- the assignee
- the candidate groups

## Related issues
closes #283

### CODE REVIEW

**Comment by skayliu** [comment]
Hi, @saig0, Please take a moment to review this feature. Thank you.

**Comment by saig0** [comment]
@skayliu thank you for your contribution. :tada: I'll have a look at your PR in the next few days. :eyes:

**Comment by saig0** [comment]
@skayliu please rebase your PR on the latest changes. There was an issue in the CI.

**Comment by skayliu** [comment]
@saig0, Done, please try again.

**Review by saig0 — APPROVED** [review]
@skayliu your changes look good. :+1: The PR is ready to merge. :tada:

**Pull request merged**
