### PR TITLE
Add the postgres driver

### LINKED ISSUE #129: Dockerfile?
I really need a Dockerfile to be able to add the Postgres jar file and in general build a new image. But for some reason there is no such thing in the repo.

Can you please assist?

### PR DESCRIPTION
**Pull request by aivinog1**
I've added the Postgres driver as a dependency so it could be available in the container app classpath.

Closes #129

### CODE REVIEW

**Comment by aivinog1** [comment]
Hey @saig0! As discussed in https://github.com/camunda-community-hub/zeeqs/issues/129#issuecomment-912243446 I've added some integration tests with Postgres Testcontainers in https://github.com/camunda-community-hub/zeeqs/pull/163/commits/7217f07e04f5c01fedff784f540a45d029fbe882.

**Comment by saig0** [comment]
@aivinog1 thank you for your contribution :tada: I'll review the PR soon.

**Comment by aivinog1** [comment]
Hey @saig0! This is a kindly reminder about this PR, in case you forgot about it :)

**Comment by saig0** [comment]
@aivinog1 I'm sorry for the delay :sweat_smile: I'll review it the beginning of next week. :cake:

**Comment by saig0** [comment]
@aivinog1 done :tada:

I did one change for the tests. Instead of using an abstract test class, I configured the surefire maven plugin to run the tests with each (h2 and postgres) supported database.

**Comment by danshapir** [comment]
@saig0 I'm unsure as to how this can be used now?

**Comment by saig0** [comment]
@danshapir I need to build a release first.

With the new release, it should be possible to configure the [Postgres datasource](https://github.com/camunda-community-hub/zeeqs#configuration) and just work. The Postgres driver is integrated.

**Comment by danshapir** [comment]
Oh great!! Can this be done for the simple monitor as well?

**Comment by saig0** [comment]
> Can this be done for the simple monitor as well?

Yes :rocket: 

Here, is the issue: https://github.com/camunda-community-hub/zeebe-simple-monitor/issues/298. I'm happy to receive contributions :sparkles:

**Pull request merged**
