### PR TITLE
Update to Zeebe 1.0.0

### PR DESCRIPTION
**Pull request by Lzgabel**
* dump zeebe version from 0.26.3 to 1.0.0
* dump hazelcast exporter version from 0.10.0 to 1.0.0

### CODE REVIEW

**Comment by saig0** [comment]
@Lzgabel thank you for your contribution :tada: 

I'll have a deeper look at it next week. Note that the next version of ZeeQS will be `2.0.0` (following semantic versioning).

**Review by saig0 — CHANGES_REQUESTED** [review]
@Lzgabel thanks for updating :rocket: 

Before I can merge your PR, we must fix the build. Currently, there are two issues:

* the parent version in `graphql-api` is not updated. In order to prepare the release, I would like set the versions to `2.0.0-SNAPSHOT` instead of `1.0.0` that was already released.
* the tests fails because `zeebe-test-container` uses Zeebe `0.26`. We can dump the version of `zeebe-test-container` to `3.0.0` that uses Zebe `1.0.0` by default.

Can you make these changes? :cake:

**Comment by Lzgabel** [comment]
@saig0 Sure, I'll do it.

**Comment by Lzgabel** [comment]
@saig0 It's done! Can you review it, please?

**Review by saig0 — APPROVED** [review]
It's working. Thanks for contributing :tada: 

I'll do a few more changes before building the release :rocket:

**Pull request merged**
